# Tensor&Variable

pytorch处理的最基本的操作对象是Tensor（张量）--多维的矩阵
## pytorch的Tensor可以和numpy的ndarray相互转换

In [4]:
import torch
import numpy as np

# 创建一个 numpy ndarray
numpy_tensor = np.random.randn(10, 20)

将numpy的ndarray转换到tensor上，且numpy的ndarry类型转换为对应的Tensor数据类型
有以下两种方法

In [2]:
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)

使用下面的方法将 pytorch tensor 转换为 numpy ndarray

In [3]:
# 如果 pytorch tensor 在 cpu 上
numpy_array = pytorch_tensor1.numpy()

# 如果 pytorch tensor 在 gpu 上
numpy_array = pytorch_tensor1.cpu().numpy()

 GPU 上的 Tensor 不能直接转换为 NumPy ndarray，需要使用.cpu()先将 GPU 上的 Tensor 转到 CPU 上
 
 我们可以使用以下两种方式将 Tensor 放到 GPU 上

In [ ]:
#方法一
dtype = torch.cuda.FloatTensor#定义数据类型为GPU
gpu_tensor = torch.randn(10,20).type(dtype)

#方法二
gpu_tensor = torch.randn(10,20).cuda(0)#第一个gpu
gpu_tensor = torch.randn(10,20).cuda(1)#第二个gpu

推荐定义tensor时指明数据类型，直接将tensor放在gpu上

tensor放回cpu

In [ ]:
cpu_tensor = gpu_tensor.cpu()

tensor的一些属性

In [4]:
#两种方式得到tensor大小
print(pytorch_tensor1.size())
print(pytorch_tensor1.shape)

torch.Size([10, 20])
torch.Size([10, 20])


In [5]:
#得到tensor的数据类型
print('tensor默认数据类型'+ pytorch_tensor1.type())

默认数据类型torch.FloatTensor


In [6]:
#得到tensor的维度
print(pytorch_tensor1.dim())

2


In [7]:
# 得到 tensor 的所有元素个数
print(pytorch_tensor1.numel())

200


创建一个 float64、大小是 3 x 2、随机初始化的 tensor，将其转化为 numpy 的 ndarray，输出其数据类型

In [12]:
tensor = torch.randn(3,2)
tensor = tensor.type(torch.DoubleTensor)
array = tensor.numpy()
print(array.dtype)

float64


## Tensor的操作(不全)

In [17]:
x = torch.ones(3,3)
print(x)
print(x.dtype)
print(x.type())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32
torch.FloatTensor


In [23]:
#随机生成
x = torch.randn(3,4)
print(x)
#每行的最大值及其下标
max_value,max_id = torch.max(x,dim=1)#列dim=0
print(max_id)
print(max_value)

tensor([[-0.5851, -0.3562,  1.8027,  0.1733],
        [ 0.7374, -0.2840, -0.9297,  0.2989],
        [-0.1979, -0.2541,  1.2602, -0.0201]])
tensor([2, 0, 2])
tensor([1.8027, 0.7374, 1.2602])


In [24]:
x = torch.randn(3, 4, 5)
print(x.shape)

# 使用permute和transpose进行维度交换
x = x.permute(1, 0, 2) # permute 可以重新排列 tensor 的维度
print(x.shape)

x = x.transpose(0, 2)  # transpose 交换 tensor 中的两个维度
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [27]:
# 使用 view 对 tensor 进行 reshape
x = torch.randn(3, 4, 5)
print(x.shape)

x = x.view(-1, 5) # -1 表示任意的大小，5 表示第二维变成 5
print(x.shape)

x = x.view(3, 20) # 重新 reshape 成 (3, 20) 的大小
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


## Variable

Variabel都有三个属性，Variable 中的 tensor本身.data，对应 tensor 的梯度.grad以及这个 Variable 是通过什么方式得到的.grad_fn

In [2]:
# 通过下面这种方式导入 Variable
from torch.autograd import Variable

In [5]:
x_tensor = torch.randn(10, 5)
y_tensor = torch.randn(10, 5)

# 将 tensor 变成 Variable
x = Variable(x_tensor, requires_grad=True) # 默认 Variable 是不需要求梯度的，所以我们用这个方式申明需要对其进行求梯度
y = Variable(y_tensor, requires_grad=True)

In [6]:
z = torch.sum(x + y)
#print(z)
print(z.data)
print(z.grad_fn)

tensor(-17.6334)


In [7]:
# 求 x 和 y 的梯度
z.backward()

print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


尝试构建一个函数 $y = x^2 $，然后求 x=2 的导数。

In [19]:
x = Variable(torch.FloatTensor([2]), requires_grad=True)
y = x ** 2
y.backward()
print((x.grad).int())
print((x.grad).int().type())

tensor([4], dtype=torch.int32)
torch.IntTensor
